// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addApplication = `-- name: AddApplication :exec
INSERT INTO
    "application" (
        id,
        tenant_id,
        name,
        is_active,
        has_mfa_auth_app,
        has_mfa_email,
        has_mfa_webauthn,
        badges,
        description,
        created_at,
        updated_at,
        can_self_sign_up,
        can_self_forgot_pass
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13
    )
`

type AddApplicationParams struct {
	ID                uuid.UUID        `db:"id"`
	TenantID          uuid.UUID        `db:"tenant_id"`
	Name              string           `db:"name"`
	IsActive          bool             `db:"is_active"`
	HasMfaAuthApp     bool             `db:"has_mfa_auth_app"`
	HasMfaEmail       bool             `db:"has_mfa_email"`
	HasMfaWebauthn    bool             `db:"has_mfa_webauthn"`
	Badges            *string          `db:"badges"`
	Description       *string          `db:"description"`
	CreatedAt         pgtype.Timestamp `db:"created_at"`
	UpdatedAt         *time.Time       `db:"updated_at"`
	CanSelfSignUp     bool             `db:"can_self_sign_up"`
	CanSelfForgotPass bool             `db:"can_self_forgot_pass"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddApplication(ctx context.Context, arg AddApplicationParams) error {
	_, err := q.db.Exec(ctx, addApplication,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.IsActive,
		arg.HasMfaAuthApp,
		arg.HasMfaEmail,
		arg.HasMfaWebauthn,
		arg.Badges,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CanSelfSignUp,
		arg.CanSelfForgotPass,
	)
	return err
}

const checkIfApplicationExists = `-- name: CheckIfApplicationExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            "application"
        WHERE
            id = $1
    )
`

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) CheckIfApplicationExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfApplicationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM
    "application"
WHERE
    id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT
    id,
    tenant_id,
    name,
    description,
    badges,
    is_active,
    has_mfa_auth_app,
    has_mfa_email,
    has_mfa_webauthn,
    created_at,
    updated_at,
    can_self_sign_up,
    can_self_forgot_pass,
    refresh_token_ttl_days,
    requires_high_security
FROM
    "application"
WHERE
    id = $1
`

type GetApplicationByIDRow struct {
	ID                   uuid.UUID        `db:"id"`
	TenantID             uuid.UUID        `db:"tenant_id"`
	Name                 string           `db:"name"`
	Description          *string          `db:"description"`
	Badges               *string          `db:"badges"`
	IsActive             bool             `db:"is_active"`
	HasMfaAuthApp        bool             `db:"has_mfa_auth_app"`
	HasMfaEmail          bool             `db:"has_mfa_email"`
	HasMfaWebauthn       bool             `db:"has_mfa_webauthn"`
	CreatedAt            pgtype.Timestamp `db:"created_at"`
	UpdatedAt            *time.Time       `db:"updated_at"`
	CanSelfSignUp        bool             `db:"can_self_sign_up"`
	CanSelfForgotPass    bool             `db:"can_self_forgot_pass"`
	RefreshTokenTtlDays  int32            `db:"refresh_token_ttl_days"`
	RequiresHighSecurity bool             `db:"requires_high_security"`
}

func (q *Queries) GetApplicationByID(ctx context.Context, id uuid.UUID) (GetApplicationByIDRow, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i GetApplicationByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Badges,
		&i.IsActive,
		&i.HasMfaAuthApp,
		&i.HasMfaEmail,
		&i.HasMfaWebauthn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanSelfSignUp,
		&i.CanSelfForgotPass,
		&i.RefreshTokenTtlDays,
		&i.RequiresHighSecurity,
	)
	return i, err
}

const listApplicationsFromTenant = `-- name: ListApplicationsFromTenant :many
SELECT
    id,
    tenant_id,
    name,
    description,
    badges,
    has_mfa_webauthn,
    created_at,
    updated_at
FROM
    "application"
WHERE
    tenant_id = $1
`

type ListApplicationsFromTenantRow struct {
	ID             uuid.UUID        `db:"id"`
	TenantID       uuid.UUID        `db:"tenant_id"`
	Name           string           `db:"name"`
	Description    *string          `db:"description"`
	Badges         *string          `db:"badges"`
	HasMfaWebauthn bool             `db:"has_mfa_webauthn"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
	UpdatedAt      *time.Time       `db:"updated_at"`
}

func (q *Queries) ListApplicationsFromTenant(ctx context.Context, tenantID uuid.UUID) ([]ListApplicationsFromTenantRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsFromTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsFromTenantRow
	for rows.Next() {
		var i ListApplicationsFromTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Badges,
			&i.HasMfaWebauthn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE
    "application"
SET
    name = $1,
    description = $2,
    has_mfa_auth_app = $3,
    has_mfa_webauthn = $4,
    badges = $5,
    is_active = $6,
    has_mfa_email = $7,
    updated_at = $8,
    can_self_sign_up = $9,
    can_self_forgot_pass = $10,
    refresh_token_ttl_days = $11,
    requires_high_security = $12
WHERE
    id = $13
`

type UpdateApplicationParams struct {
	Name                 string     `db:"name"`
	Description          *string    `db:"description"`
	HasMfaAuthApp        bool       `db:"has_mfa_auth_app"`
	HasMfaWebauthn       bool       `db:"has_mfa_webauthn"`
	Badges               *string    `db:"badges"`
	IsActive             bool       `db:"is_active"`
	HasMfaEmail          bool       `db:"has_mfa_email"`
	UpdatedAt            *time.Time `db:"updated_at"`
	CanSelfSignUp        bool       `db:"can_self_sign_up"`
	CanSelfForgotPass    bool       `db:"can_self_forgot_pass"`
	RefreshTokenTtlDays  int32      `db:"refresh_token_ttl_days"`
	RequiresHighSecurity bool       `db:"requires_high_security"`
	ID                   uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.Exec(ctx, updateApplication,
		arg.Name,
		arg.Description,
		arg.HasMfaAuthApp,
		arg.HasMfaWebauthn,
		arg.Badges,
		arg.IsActive,
		arg.HasMfaEmail,
		arg.UpdatedAt,
		arg.CanSelfSignUp,
		arg.CanSelfForgotPass,
		arg.RefreshTokenTtlDays,
		arg.RequiresHighSecurity,
		arg.ID,
	)
	return err
}
