// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAuditLog = `-- name: AddAuditLog :exec
INSERT INTO
  audit_log (
    id,
    user_id,
    application_id,
    event_type,
    ip_address,
    user_agent,
    result,
    details,
    created_at
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
  )
`

type AddAuditLogParams struct {
	ID            uuid.UUID        `db:"id"`
	UserID        uuid.UUID        `db:"user_id"`
	ApplicationID uuid.UUID        `db:"application_id"`
	EventType     string           `db:"event_type"`
	IpAddress     string           `db:"ip_address"`
	UserAgent     string           `db:"user_agent"`
	Result        string           `db:"result"`
	Details       *string          `db:"details"`
	CreatedAt     pgtype.Timestamp `db:"created_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddAuditLog(ctx context.Context, arg AddAuditLogParams) error {
	_, err := q.db.Exec(ctx, addAuditLog,
		arg.ID,
		arg.UserID,
		arg.ApplicationID,
		arg.EventType,
		arg.IpAddress,
		arg.UserAgent,
		arg.Result,
		arg.Details,
		arg.CreatedAt,
	)
	return err
}

const getAuditLogsByUserID = `-- name: GetAuditLogsByUserID :many
SELECT
  id,
  user_id,
  application_id,
  event_type,
  ip_address,
  user_agent,
  result,
  details,
  created_at
FROM
  audit_log
WHERE
  user_id = $1
ORDER BY
  created_at DESC
LIMIT
  $3 OFFSET $2
`

type GetAuditLogsByUserIDParams struct {
	UserID      uuid.UUID `db:"user_id"`
	OffsetCount int32     `db:"offset_count"`
	LimitCount  int32     `db:"limit_count"`
}

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetAuditLogsByUserID(ctx context.Context, arg GetAuditLogsByUserIDParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByUserID, arg.UserID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApplicationID,
			&i.EventType,
			&i.IpAddress,
			&i.UserAgent,
			&i.Result,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
