// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorization_session.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAuthorizationSession = `-- name: AddAuthorizationSession :exec
INSERT INTO
    authorization_session (
        id,
        user_id,
        token,
        created_at,
        expires_at,
        is_used
    )
VALUES
    (
        $1,
        -- id
        $2,
        -- user_id
        -- email
        $3,
        -- token
        $4,
        -- created_at
        $5,
        -- expires_at
        $6 -- is_used
    )
`

type AddAuthorizationSessionParams struct {
	ID        uuid.UUID        `db:"id"`
	UserID    uuid.UUID        `db:"user_id"`
	Token     string           `db:"token"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	ExpiresAt pgtype.Timestamp `db:"expires_at"`
	IsUsed    bool             `db:"is_used"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddAuthorizationSession(ctx context.Context, arg AddAuthorizationSessionParams) error {
	_, err := q.db.Exec(ctx, addAuthorizationSession,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.IsUsed,
	)
	return err
}

const deleteAuthorizationSession = `-- name: DeleteAuthorizationSession :exec
DELETE FROM
    authorization_session
WHERE
    id = $1
`

func (q *Queries) DeleteAuthorizationSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthorizationSession, id)
	return err
}

const getAuthorizationSession = `-- name: GetAuthorizationSession :one
SELECT
    id,
    user_id,
    token,
    created_at,
    expires_at,
    is_used
FROM
    authorization_session
WHERE
    user_id = $1
    AND token = $2
`

type GetAuthorizationSessionParams struct {
	UserID uuid.UUID `db:"user_id"`
	Token  string    `db:"token"`
}

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetAuthorizationSession(ctx context.Context, arg GetAuthorizationSessionParams) (AuthorizationSession, error) {
	row := q.db.QueryRow(ctx, getAuthorizationSession, arg.UserID, arg.Token)
	var i AuthorizationSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsUsed,
	)
	return i, err
}

const revokeAuthorizationSession = `-- name: RevokeAuthorizationSession :exec
DELETE FROM
    authorization_session
WHERE
    user_id = $1
`

func (q *Queries) RevokeAuthorizationSession(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAuthorizationSession, userID)
	return err
}

const updateAuthorizationSession = `-- name: UpdateAuthorizationSession :exec
UPDATE
    authorization_session
SET
    user_id = $1,
    token = $2,
    created_at = $3,
    expires_at = $4,
    is_used = $5
WHERE
    id = $6
`

type UpdateAuthorizationSessionParams struct {
	UserID    uuid.UUID        `db:"user_id"`
	Token     string           `db:"token"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	ExpiresAt pgtype.Timestamp `db:"expires_at"`
	IsUsed    bool             `db:"is_used"`
	ID        uuid.UUID        `db:"id"`
}

func (q *Queries) UpdateAuthorizationSession(ctx context.Context, arg UpdateAuthorizationSessionParams) error {
	_, err := q.db.Exec(ctx, updateAuthorizationSession,
		arg.UserID,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.IsUsed,
		arg.ID,
	)
	return err
}
