// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backup_code.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBackupCode = `-- name: AddBackupCode :exec
INSERT INTO
  backup_code (
    id,
    user_id,
    code_hash,
    is_used,
    created_at,
    used_at
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
  )
`

type AddBackupCodeParams struct {
	ID        uuid.UUID        `db:"id"`
	UserID    uuid.UUID        `db:"user_id"`
	CodeHash  string           `db:"code_hash"`
	IsUsed    bool             `db:"is_used"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UsedAt    *time.Time       `db:"used_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddBackupCode(ctx context.Context, arg AddBackupCodeParams) error {
	_, err := q.db.Exec(ctx, addBackupCode,
		arg.ID,
		arg.UserID,
		arg.CodeHash,
		arg.IsUsed,
		arg.CreatedAt,
		arg.UsedAt,
	)
	return err
}

const countUnusedBackupCodesByUserID = `-- name: CountUnusedBackupCodesByUserID :one
SELECT
  COUNT(*)
FROM
  backup_code
WHERE
  user_id = $1
  AND is_used = FALSE
`

func (q *Queries) CountUnusedBackupCodesByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedBackupCodesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBackupCodesByUserID = `-- name: DeleteBackupCodesByUserID :exec
DELETE FROM
  backup_code
WHERE
  user_id = $1
`

func (q *Queries) DeleteBackupCodesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackupCodesByUserID, userID)
	return err
}

const getUnusedBackupCodesByUserID = `-- name: GetUnusedBackupCodesByUserID :many
SELECT
  id,
  user_id,
  code_hash,
  is_used,
  created_at,
  used_at
FROM
  backup_code
WHERE
  user_id = $1
  AND is_used = FALSE
`

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetUnusedBackupCodesByUserID(ctx context.Context, userID uuid.UUID) ([]BackupCode, error) {
	rows, err := q.db.Query(ctx, getUnusedBackupCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupCode
	for rows.Next() {
		var i BackupCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.IsUsed,
			&i.CreatedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupCodeUsed = `-- name: MarkBackupCodeUsed :exec
UPDATE
  backup_code
SET
  is_used = TRUE,
  used_at = NOW()
WHERE
  id = $1
`

func (q *Queries) MarkBackupCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackupCodeUsed, id)
	return err
}
