// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: change_password_code.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addChangePasswordCode = `-- name: AddChangePasswordCode :exec
INSERT INTO
    change_password_code (
        id,
        user_id,
        email,
        token,
        created_at,
        expires_at
    )
VALUES
    (
        $1,
        -- id
        $2,
        -- user_id
        $3,
        -- email
        $4,
        -- token
        $5,
        -- created_at
        $6 -- expires_at
    )
`

type AddChangePasswordCodeParams struct {
	ID        uuid.UUID        `db:"id"`
	UserID    uuid.UUID        `db:"user_id"`
	Email     string           `db:"email"`
	Token     string           `db:"token"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	ExpiresAt pgtype.Timestamp `db:"expires_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddChangePasswordCode(ctx context.Context, arg AddChangePasswordCodeParams) error {
	_, err := q.db.Exec(ctx, addChangePasswordCode,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteChangePasswordCode = `-- name: DeleteChangePasswordCode :exec
DELETE FROM
    change_password_code
WHERE
    id = $1
`

func (q *Queries) DeleteChangePasswordCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChangePasswordCode, id)
	return err
}

const getChangePasswordCodeByToken = `-- name: GetChangePasswordCodeByToken :one
SELECT
    id,
    user_id,
    email,
    token,
    created_at,
    expires_at
FROM
    change_password_code
WHERE
    user_id = $1
    AND token = $2
`

type GetChangePasswordCodeByTokenParams struct {
	UserID uuid.UUID `db:"user_id"`
	Token  string    `db:"token"`
}

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetChangePasswordCodeByToken(ctx context.Context, arg GetChangePasswordCodeByTokenParams) (ChangePasswordCode, error) {
	row := q.db.QueryRow(ctx, getChangePasswordCodeByToken, arg.UserID, arg.Token)
	var i ChangePasswordCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeChangePasswordCodeByUserID = `-- name: RevokeChangePasswordCodeByUserID :exec
DELETE FROM
    change_password_code
WHERE
    user_id = $1
`

func (q *Queries) RevokeChangePasswordCodeByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeChangePasswordCodeByUserID, userID)
	return err
}

const updateChangePasswordCode = `-- name: UpdateChangePasswordCode :exec
UPDATE
    change_password_code
SET
    user_id = $1,
    email = $2,
    token = $3,
    created_at = $4,
    expires_at = $5
WHERE
    id = $6
`

type UpdateChangePasswordCodeParams struct {
	UserID    uuid.UUID        `db:"user_id"`
	Email     string           `db:"email"`
	Token     string           `db:"token"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	ExpiresAt pgtype.Timestamp `db:"expires_at"`
	ID        uuid.UUID        `db:"id"`
}

func (q *Queries) UpdateChangePasswordCode(ctx context.Context, arg UpdateChangePasswordCodeParams) error {
	_, err := q.db.Exec(ctx, updateChangePasswordCode,
		arg.UserID,
		arg.Email,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
