// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_change_request.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEmailChangeRequest = `-- name: AddEmailChangeRequest :exec
INSERT INTO
  email_change_request (
    id,
    user_id,
    application_id,
    new_email,
    token,
    created_at,
    expires_at,
    is_confirmed
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
  )
`

type AddEmailChangeRequestParams struct {
	ID            uuid.UUID        `db:"id"`
	UserID        uuid.UUID        `db:"user_id"`
	ApplicationID uuid.UUID        `db:"application_id"`
	NewEmail      string           `db:"new_email"`
	Token         string           `db:"token"`
	CreatedAt     pgtype.Timestamp `db:"created_at"`
	ExpiresAt     pgtype.Timestamp `db:"expires_at"`
	IsConfirmed   bool             `db:"is_confirmed"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddEmailChangeRequest(ctx context.Context, arg AddEmailChangeRequestParams) error {
	_, err := q.db.Exec(ctx, addEmailChangeRequest,
		arg.ID,
		arg.UserID,
		arg.ApplicationID,
		arg.NewEmail,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.IsConfirmed,
	)
	return err
}

const confirmEmailChangeRequest = `-- name: ConfirmEmailChangeRequest :exec
UPDATE
  email_change_request
SET
  is_confirmed = TRUE
WHERE
  id = $1
`

func (q *Queries) ConfirmEmailChangeRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmEmailChangeRequest, id)
	return err
}

const getEmailChangeRequestByToken = `-- name: GetEmailChangeRequestByToken :one
SELECT
  id,
  user_id,
  application_id,
  new_email,
  token,
  created_at,
  expires_at,
  is_confirmed
FROM
  email_change_request
WHERE
  token = $1
  AND is_confirmed = FALSE
`

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetEmailChangeRequestByToken(ctx context.Context, token string) (EmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, getEmailChangeRequestByToken, token)
	var i EmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.NewEmail,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsConfirmed,
	)
	return i, err
}

const revokeEmailChangeRequestsByUserID = `-- name: RevokeEmailChangeRequestsByUserID :exec
DELETE FROM
  email_change_request
WHERE
  user_id = $1
  AND is_confirmed = FALSE
`

func (q *Queries) RevokeEmailChangeRequestsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeEmailChangeRequestsByUserID, userID)
	return err
}
