// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_oauth_state.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addExternalOAuthState = `-- name: AddExternalOAuthState :exec
INSERT INTO
  external_oauth_state (
    id,
    provider_state,
    application_oauth_provider_id,
    client_state,
    client_code_challenge_method,
    client_code_challenge,
    client_scope,
    code_verifier,
    client_response_type,
    client_redirect_uri,
    created_at
  )
VALUES
  (
    $1,
    -- id
    $2,
    -- state
    $3,
    -- application_oauth_provider_id
    $4,
    -- client_state
    $5,
    -- client_code_challenge_method
    $6,
    -- client_code_challenge
    $7,
    -- client_scope
    $8,
    -- code_verifier
    $9,
    -- client_response_type
    $10,
    -- client_redirect_uri
    $11 -- created_at
  )
`

type AddExternalOAuthStateParams struct {
	ID                         uuid.UUID        `db:"id"`
	ProviderState              string           `db:"provider_state"`
	ApplicationOauthProviderID uuid.UUID        `db:"application_oauth_provider_id"`
	ClientState                *string          `db:"client_state"`
	ClientCodeChallengeMethod  *string          `db:"client_code_challenge_method"`
	ClientCodeChallenge        *string          `db:"client_code_challenge"`
	ClientScope                *string          `db:"client_scope"`
	CodeVerifier               string           `db:"code_verifier"`
	ClientResponseType         *string          `db:"client_response_type"`
	ClientRedirectUri          *string          `db:"client_redirect_uri"`
	CreatedAt                  pgtype.Timestamp `db:"created_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddExternalOAuthState(ctx context.Context, arg AddExternalOAuthStateParams) error {
	_, err := q.db.Exec(ctx, addExternalOAuthState,
		arg.ID,
		arg.ProviderState,
		arg.ApplicationOauthProviderID,
		arg.ClientState,
		arg.ClientCodeChallengeMethod,
		arg.ClientCodeChallenge,
		arg.ClientScope,
		arg.CodeVerifier,
		arg.ClientResponseType,
		arg.ClientRedirectUri,
		arg.CreatedAt,
	)
	return err
}

const getExternalOAuthStateByState = `-- name: GetExternalOAuthStateByState :one
SELECT
  id,
  provider_state,
  application_oauth_provider_id,
  client_state,
  client_code_challenge_method,
  client_code_challenge,
  client_scope,
  code_verifier,
  client_response_type,
  client_redirect_uri,
  created_at
FROM
  external_oauth_state
WHERE
  provider_state = $1
`

type GetExternalOAuthStateByStateRow struct {
	ID                         uuid.UUID        `db:"id"`
	ProviderState              string           `db:"provider_state"`
	ApplicationOauthProviderID uuid.UUID        `db:"application_oauth_provider_id"`
	ClientState                *string          `db:"client_state"`
	ClientCodeChallengeMethod  *string          `db:"client_code_challenge_method"`
	ClientCodeChallenge        *string          `db:"client_code_challenge"`
	ClientScope                *string          `db:"client_scope"`
	CodeVerifier               string           `db:"code_verifier"`
	ClientResponseType         *string          `db:"client_response_type"`
	ClientRedirectUri          *string          `db:"client_redirect_uri"`
	CreatedAt                  pgtype.Timestamp `db:"created_at"`
}

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetExternalOAuthStateByState(ctx context.Context, providerState string) (GetExternalOAuthStateByStateRow, error) {
	row := q.db.QueryRow(ctx, getExternalOAuthStateByState, providerState)
	var i GetExternalOAuthStateByStateRow
	err := row.Scan(
		&i.ID,
		&i.ProviderState,
		&i.ApplicationOauthProviderID,
		&i.ClientState,
		&i.ClientCodeChallengeMethod,
		&i.ClientCodeChallenge,
		&i.ClientScope,
		&i.CodeVerifier,
		&i.ClientResponseType,
		&i.ClientRedirectUri,
		&i.CreatedAt,
	)
	return i, err
}
