// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_identity.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addExternalIdentity = `-- name: AddExternalIdentity :exec
INSERT INTO
    external_identity (
        id,
        user_id,
        email,
        provider,
        provider_user_id,
        application_oauth_provider_id,
        created_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
`

type AddExternalIdentityParams struct {
	ID                         uuid.UUID        `db:"id"`
	UserID                     uuid.UUID        `db:"user_id"`
	Email                      string           `db:"email"`
	Provider                   string           `db:"provider"`
	ProviderUserID             string           `db:"provider_user_id"`
	ApplicationOauthProviderID uuid.UUID        `db:"application_oauth_provider_id"`
	CreatedAt                  pgtype.Timestamp `db:"created_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddExternalIdentity(ctx context.Context, arg AddExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, addExternalIdentity,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.Provider,
		arg.ProviderUserID,
		arg.ApplicationOauthProviderID,
		arg.CreatedAt,
	)
	return err
}

const getExternalIdentitiesByUserID = `-- name: GetExternalIdentitiesByUserID :many
SELECT
    id,
    user_id,
    email,
    provider,
    provider_user_id,
    application_oauth_provider_id,
    created_at,
    updated_at
FROM
    external_identity
WHERE
    user_id = $1
`

func (q *Queries) GetExternalIdentitiesByUserID(ctx context.Context, userID uuid.UUID) ([]ExternalIdentity, error) {
	rows, err := q.db.Query(ctx, getExternalIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalIdentity
	for rows.Next() {
		var i ExternalIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Provider,
			&i.ProviderUserID,
			&i.ApplicationOauthProviderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExternalIdentityByProviderUserId = `-- name: GetExternalIdentityByProviderUserId :one
SELECT
    id,
    user_id,
    email,
    provider,
    provider_user_id,
    application_oauth_provider_id,
    created_at,
    updated_at
FROM
    external_identity
WHERE
    provider = $1
    AND provider_user_id = $2
`

type GetExternalIdentityByProviderUserIdParams struct {
	Provider       string `db:"provider"`
	ProviderUserID string `db:"provider_user_id"`
}

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetExternalIdentityByProviderUserId(ctx context.Context, arg GetExternalIdentityByProviderUserIdParams) (ExternalIdentity, error) {
	row := q.db.QueryRow(ctx, getExternalIdentityByProviderUserId, arg.Provider, arg.ProviderUserID)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Provider,
		&i.ProviderUserID,
		&i.ApplicationOauthProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
