// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa_passkey_credentials.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMfaPasskeyCredential = `-- name: AddMfaPasskeyCredential :exec
INSERT INTO
    mfa_passkey_credentials (
        id,
        mfa_method_id,
        credential_id,
        public_key,
        sign_count,
        backup_eligible,
        backup_state,
        created_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
`

type AddMfaPasskeyCredentialParams struct {
	ID             uuid.UUID        `db:"id"`
	MfaMethodID    uuid.UUID        `db:"mfa_method_id"`
	CredentialID   string           `db:"credential_id"`
	PublicKey      string           `db:"public_key"`
	SignCount      int32            `db:"sign_count"`
	BackupEligible bool             `db:"backup_eligible"`
	BackupState    bool             `db:"backup_state"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddMfaPasskeyCredential(ctx context.Context, arg AddMfaPasskeyCredentialParams) error {
	_, err := q.db.Exec(ctx, addMfaPasskeyCredential,
		arg.ID,
		arg.MfaMethodID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.BackupEligible,
		arg.BackupState,
		arg.CreatedAt,
	)
	return err
}

const deleteMfaPasskeyCredential = `-- name: DeleteMfaPasskeyCredential :exec
DELETE FROM
    mfa_passkey_credentials
WHERE
    id = $1
`

func (q *Queries) DeleteMfaPasskeyCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMfaPasskeyCredential, id)
	return err
}

const getMfaPasskeyCredentialByCredentialID = `-- name: GetMfaPasskeyCredentialByCredentialID :one
SELECT
    id,
    mfa_method_id,
    credential_id,
    public_key,
    sign_count,
    backup_eligible,
    backup_state,
    created_at
FROM
    mfa_passkey_credentials
WHERE
    credential_id = $1
    AND mfa_method_id = $2
`

type GetMfaPasskeyCredentialByCredentialIDParams struct {
	CredentialID string    `db:"credential_id"`
	MfaMethodID  uuid.UUID `db:"mfa_method_id"`
}

type GetMfaPasskeyCredentialByCredentialIDRow struct {
	ID             uuid.UUID        `db:"id"`
	MfaMethodID    uuid.UUID        `db:"mfa_method_id"`
	CredentialID   string           `db:"credential_id"`
	PublicKey      string           `db:"public_key"`
	SignCount      int32            `db:"sign_count"`
	BackupEligible bool             `db:"backup_eligible"`
	BackupState    bool             `db:"backup_state"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
}

func (q *Queries) GetMfaPasskeyCredentialByCredentialID(ctx context.Context, arg GetMfaPasskeyCredentialByCredentialIDParams) (GetMfaPasskeyCredentialByCredentialIDRow, error) {
	row := q.db.QueryRow(ctx, getMfaPasskeyCredentialByCredentialID, arg.CredentialID, arg.MfaMethodID)
	var i GetMfaPasskeyCredentialByCredentialIDRow
	err := row.Scan(
		&i.ID,
		&i.MfaMethodID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.CreatedAt,
	)
	return i, err
}

const getMfaPasskeyCredentialsByMfaMethodID = `-- name: GetMfaPasskeyCredentialsByMfaMethodID :many
SELECT
    id,
    mfa_method_id,
    credential_id,
    public_key,
    sign_count,
    backup_eligible,
    backup_state,
    created_at
FROM
    mfa_passkey_credentials
WHERE
    mfa_method_id = $1
`

type GetMfaPasskeyCredentialsByMfaMethodIDRow struct {
	ID             uuid.UUID        `db:"id"`
	MfaMethodID    uuid.UUID        `db:"mfa_method_id"`
	CredentialID   string           `db:"credential_id"`
	PublicKey      string           `db:"public_key"`
	SignCount      int32            `db:"sign_count"`
	BackupEligible bool             `db:"backup_eligible"`
	BackupState    bool             `db:"backup_state"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
}

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetMfaPasskeyCredentialsByMfaMethodID(ctx context.Context, mfaMethodID uuid.UUID) ([]GetMfaPasskeyCredentialsByMfaMethodIDRow, error) {
	rows, err := q.db.Query(ctx, getMfaPasskeyCredentialsByMfaMethodID, mfaMethodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMfaPasskeyCredentialsByMfaMethodIDRow
	for rows.Next() {
		var i GetMfaPasskeyCredentialsByMfaMethodIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MfaMethodID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.BackupEligible,
			&i.BackupState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMfaPasskeyCredentialSignCount = `-- name: UpdateMfaPasskeyCredentialSignCount :exec
UPDATE
    mfa_passkey_credentials
SET
    sign_count = $1
WHERE
    id = $2
`

type UpdateMfaPasskeyCredentialSignCountParams struct {
	SignCount int32     `db:"sign_count"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateMfaPasskeyCredentialSignCount(ctx context.Context, arg UpdateMfaPasskeyCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateMfaPasskeyCredentialSignCount, arg.SignCount, arg.ID)
	return err
}
