// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa_webauthn_credentials.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMfaWebauthnCredential = `-- name: AddMfaWebauthnCredential :exec
INSERT INTO
    mfa_webauthn_credentials (
        id,
        mfa_method_id,
        credential_id,
        public_key,
        sign_count,
        backup_eligible,
        backup_state,
        created_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
`

type AddMfaWebauthnCredentialParams struct {
	ID             uuid.UUID        `db:"id"`
	MfaMethodID    uuid.UUID        `db:"mfa_method_id"`
	CredentialID   string           `db:"credential_id"`
	PublicKey      string           `db:"public_key"`
	SignCount      int32            `db:"sign_count"`
	BackupEligible bool             `db:"backup_eligible"`
	BackupState    bool             `db:"backup_state"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddMfaWebauthnCredential(ctx context.Context, arg AddMfaWebauthnCredentialParams) error {
	_, err := q.db.Exec(ctx, addMfaWebauthnCredential,
		arg.ID,
		arg.MfaMethodID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.BackupEligible,
		arg.BackupState,
		arg.CreatedAt,
	)
	return err
}

const deleteMfaWebauthnCredential = `-- name: DeleteMfaWebauthnCredential :exec
DELETE FROM
    mfa_webauthn_credentials
WHERE
    id = $1
`

func (q *Queries) DeleteMfaWebauthnCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMfaWebauthnCredential, id)
	return err
}

const getMfaWebauthnCredentialByCredentialID = `-- name: GetMfaWebauthnCredentialByCredentialID :one
SELECT
    id,
    mfa_method_id,
    credential_id,
    public_key,
    sign_count,
    backup_eligible,
    backup_state,
    created_at
FROM
    mfa_webauthn_credentials
WHERE
    credential_id = $1
    AND mfa_method_id = $2
`

type GetMfaWebauthnCredentialByCredentialIDParams struct {
	CredentialID string    `db:"credential_id"`
	MfaMethodID  uuid.UUID `db:"mfa_method_id"`
}

type GetMfaWebauthnCredentialByCredentialIDRow struct {
	ID             uuid.UUID        `db:"id"`
	MfaMethodID    uuid.UUID        `db:"mfa_method_id"`
	CredentialID   string           `db:"credential_id"`
	PublicKey      string           `db:"public_key"`
	SignCount      int32            `db:"sign_count"`
	BackupEligible bool             `db:"backup_eligible"`
	BackupState    bool             `db:"backup_state"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
}

func (q *Queries) GetMfaWebauthnCredentialByCredentialID(ctx context.Context, arg GetMfaWebauthnCredentialByCredentialIDParams) (GetMfaWebauthnCredentialByCredentialIDRow, error) {
	row := q.db.QueryRow(ctx, getMfaWebauthnCredentialByCredentialID, arg.CredentialID, arg.MfaMethodID)
	var i GetMfaWebauthnCredentialByCredentialIDRow
	err := row.Scan(
		&i.ID,
		&i.MfaMethodID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.CreatedAt,
	)
	return i, err
}

const getMfaWebauthnCredentialsByMfaMethodID = `-- name: GetMfaWebauthnCredentialsByMfaMethodID :many
SELECT
    id,
    mfa_method_id,
    credential_id,
    public_key,
    sign_count,
    backup_eligible,
    backup_state,
    created_at
FROM
    mfa_webauthn_credentials
WHERE
    mfa_method_id = $1
`

type GetMfaWebauthnCredentialsByMfaMethodIDRow struct {
	ID             uuid.UUID        `db:"id"`
	MfaMethodID    uuid.UUID        `db:"mfa_method_id"`
	CredentialID   string           `db:"credential_id"`
	PublicKey      string           `db:"public_key"`
	SignCount      int32            `db:"sign_count"`
	BackupEligible bool             `db:"backup_eligible"`
	BackupState    bool             `db:"backup_state"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
}

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetMfaWebauthnCredentialsByMfaMethodID(ctx context.Context, mfaMethodID uuid.UUID) ([]GetMfaWebauthnCredentialsByMfaMethodIDRow, error) {
	rows, err := q.db.Query(ctx, getMfaWebauthnCredentialsByMfaMethodID, mfaMethodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMfaWebauthnCredentialsByMfaMethodIDRow
	for rows.Next() {
		var i GetMfaWebauthnCredentialsByMfaMethodIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MfaMethodID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.BackupEligible,
			&i.BackupState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMfaWebauthnCredentialSignCount = `-- name: UpdateMfaWebauthnCredentialSignCount :exec
UPDATE
    mfa_webauthn_credentials
SET
    sign_count = $1
WHERE
    id = $2
`

type UpdateMfaWebauthnCredentialSignCountParams struct {
	SignCount int32     `db:"sign_count"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateMfaWebauthnCredentialSignCount(ctx context.Context, arg UpdateMfaWebauthnCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateMfaWebauthnCredentialSignCount, arg.SignCount, arg.ID)
	return err
}
