// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa_totp_secret_validation.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMfaTotpSecretValidation = `-- name: AddMfaTotpSecretValidation :exec
INSERT INTO
    mfa_totp_secret_validation (
        id,
        user_id,
        secret,
        is_validated,
        created_at,
        expires_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
`

type AddMfaTotpSecretValidationParams struct {
	ID          uuid.UUID        `db:"id"`
	UserID      uuid.UUID        `db:"user_id"`
	Secret      string           `db:"secret"`
	IsValidated bool             `db:"is_validated"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddMfaTotpSecretValidation(ctx context.Context, arg AddMfaTotpSecretValidationParams) error {
	_, err := q.db.Exec(ctx, addMfaTotpSecretValidation,
		arg.ID,
		arg.UserID,
		arg.Secret,
		arg.IsValidated,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getMfaTotpSecretValidationByUserId = `-- name: GetMfaTotpSecretValidationByUserId :one
SELECT
    id,
    user_id,
    secret,
    is_validated,
    created_at,
    expires_at
FROM
    mfa_totp_secret_validation
WHERE
    user_id = $1
`

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetMfaTotpSecretValidationByUserId(ctx context.Context, userID uuid.UUID) (MfaTotpSecretValidation, error) {
	row := q.db.QueryRow(ctx, getMfaTotpSecretValidationByUserId, userID)
	var i MfaTotpSecretValidation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.IsValidated,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeMfaTotpSecretValidationFromUser = `-- name: RevokeMfaTotpSecretValidationFromUser :exec
DELETE FROM
    mfa_totp_secret_validation
WHERE
    user_id = $1
`

func (q *Queries) RevokeMfaTotpSecretValidationFromUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeMfaTotpSecretValidationFromUser, userID)
	return err
}

const updateMfaTotpSecretValidation = `-- name: UpdateMfaTotpSecretValidation :exec
UPDATE
    mfa_totp_secret_validation
SET
    secret = $1,
    is_validated = $2,
    created_at = $3,
    expires_at = $4
WHERE
    id = $5
`

type UpdateMfaTotpSecretValidationParams struct {
	Secret      string           `db:"secret"`
	IsValidated bool             `db:"is_validated"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at"`
	ID          uuid.UUID        `db:"id"`
}

func (q *Queries) UpdateMfaTotpSecretValidation(ctx context.Context, arg UpdateMfaTotpSecretValidationParams) error {
	_, err := q.db.Exec(ctx, updateMfaTotpSecretValidation,
		arg.Secret,
		arg.IsValidated,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
