// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa_passkey_session.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMfaPasskeySession = `-- name: AddMfaPasskeySession :exec
INSERT INTO
    mfa_passkey_session (
        id,
        user_id,
        session_data,
        created_at,
        expires_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5
    )
`

type AddMfaPasskeySessionParams struct {
	ID          uuid.UUID        `db:"id"`
	UserID      uuid.UUID        `db:"user_id"`
	SessionData string           `db:"session_data"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddMfaPasskeySession(ctx context.Context, arg AddMfaPasskeySessionParams) error {
	_, err := q.db.Exec(ctx, addMfaPasskeySession,
		arg.ID,
		arg.UserID,
		arg.SessionData,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteMfaPasskeySession = `-- name: DeleteMfaPasskeySession :exec
DELETE FROM
    mfa_passkey_session
WHERE
    id = $1
`

func (q *Queries) DeleteMfaPasskeySession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMfaPasskeySession, id)
	return err
}

const deleteMfaPasskeySessionsByUserID = `-- name: DeleteMfaPasskeySessionsByUserID :exec
DELETE FROM
    mfa_passkey_session
WHERE
    user_id = $1
`

func (q *Queries) DeleteMfaPasskeySessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMfaPasskeySessionsByUserID, userID)
	return err
}

const getMfaPasskeySessionByID = `-- name: GetMfaPasskeySessionByID :one
SELECT
    id,
    user_id,
    session_data,
    created_at,
    expires_at
FROM
    mfa_passkey_session
WHERE
    id = $1
`

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetMfaPasskeySessionByID(ctx context.Context, id uuid.UUID) (MfaPasskeySession, error) {
	row := q.db.QueryRow(ctx, getMfaPasskeySessionByID, id)
	var i MfaPasskeySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
