// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa_webauthn_session.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMfaWebauthnSession = `-- name: AddMfaWebauthnSession :exec
INSERT INTO
    mfa_webauthn_session (
        id,
        user_id,
        session_data,
        created_at,
        expires_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5
    )
`

type AddMfaWebauthnSessionParams struct {
	ID          uuid.UUID        `db:"id"`
	UserID      uuid.UUID        `db:"user_id"`
	SessionData string           `db:"session_data"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddMfaWebauthnSession(ctx context.Context, arg AddMfaWebauthnSessionParams) error {
	_, err := q.db.Exec(ctx, addMfaWebauthnSession,
		arg.ID,
		arg.UserID,
		arg.SessionData,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteMfaWebauthnSession = `-- name: DeleteMfaWebauthnSession :exec
DELETE FROM
    mfa_webauthn_session
WHERE
    id = $1
`

func (q *Queries) DeleteMfaWebauthnSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMfaWebauthnSession, id)
	return err
}

const deleteMfaWebauthnSessionsByUserID = `-- name: DeleteMfaWebauthnSessionsByUserID :exec
DELETE FROM
    mfa_webauthn_session
WHERE
    user_id = $1
`

func (q *Queries) DeleteMfaWebauthnSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMfaWebauthnSessionsByUserID, userID)
	return err
}

const getMfaWebauthnSessionByID = `-- name: GetMfaWebauthnSessionByID :one
SELECT
    id,
    user_id,
    session_data,
    created_at,
    expires_at
FROM
    mfa_webauthn_session
WHERE
    id = $1
`

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetMfaWebauthnSessionByID(ctx context.Context, id uuid.UUID) (MfaWebauthnSession, error) {
	row := q.db.QueryRow(ctx, getMfaWebauthnSessionByID, id)
	var i MfaWebauthnSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
