// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: step_up_token.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addStepUpToken = `-- name: AddStepUpToken :exec
INSERT INTO
  step_up_token (
    id,
    user_id,
    application_id,
    token,
    created_at,
    expires_at,
    is_used
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
  )
`

type AddStepUpTokenParams struct {
	ID            uuid.UUID        `db:"id"`
	UserID        uuid.UUID        `db:"user_id"`
	ApplicationID uuid.UUID        `db:"application_id"`
	Token         string           `db:"token"`
	CreatedAt     pgtype.Timestamp `db:"created_at"`
	ExpiresAt     pgtype.Timestamp `db:"expires_at"`
	IsUsed        bool             `db:"is_used"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddStepUpToken(ctx context.Context, arg AddStepUpTokenParams) error {
	_, err := q.db.Exec(ctx, addStepUpToken,
		arg.ID,
		arg.UserID,
		arg.ApplicationID,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.IsUsed,
	)
	return err
}

const getStepUpTokenByToken = `-- name: GetStepUpTokenByToken :one
SELECT
  id,
  user_id,
  application_id,
  token,
  created_at,
  expires_at,
  is_used
FROM
  step_up_token
WHERE
  token = $1
  AND user_id = $2
`

type GetStepUpTokenByTokenParams struct {
	Token  string    `db:"token"`
	UserID uuid.UUID `db:"user_id"`
}

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetStepUpTokenByToken(ctx context.Context, arg GetStepUpTokenByTokenParams) (StepUpToken, error) {
	row := q.db.QueryRow(ctx, getStepUpTokenByToken, arg.Token, arg.UserID)
	var i StepUpToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsUsed,
	)
	return i, err
}

const markStepUpTokenUsed = `-- name: MarkStepUpTokenUsed :exec
UPDATE
  step_up_token
SET
  is_used = TRUE
WHERE
  id = $1
`

func (q *Queries) MarkStepUpTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markStepUpTokenUsed, id)
	return err
}

const revokeStepUpTokensByUserID = `-- name: RevokeStepUpTokensByUserID :exec
DELETE FROM
  step_up_token
WHERE
  user_id = $1
`

func (q *Queries) RevokeStepUpTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeStepUpTokensByUserID, userID)
	return err
}
