// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_session.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserSession = `-- name: AddUserSession :exec
INSERT INTO
  user_session (
    id,
    user_id,
    application_id,
    ip_address,
    user_agent,
    location,
    created_at,
    last_active_at,
    expires_at,
    is_revoked
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
  )
`

type AddUserSessionParams struct {
	ID            uuid.UUID        `db:"id"`
	UserID        uuid.UUID        `db:"user_id"`
	ApplicationID uuid.UUID        `db:"application_id"`
	IpAddress     string           `db:"ip_address"`
	UserAgent     string           `db:"user_agent"`
	Location      *string          `db:"location"`
	CreatedAt     pgtype.Timestamp `db:"created_at"`
	LastActiveAt  pgtype.Timestamp `db:"last_active_at"`
	ExpiresAt     pgtype.Timestamp `db:"expires_at"`
	IsRevoked     bool             `db:"is_revoked"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddUserSession(ctx context.Context, arg AddUserSessionParams) error {
	_, err := q.db.Exec(ctx, addUserSession,
		arg.ID,
		arg.UserID,
		arg.ApplicationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Location,
		arg.CreatedAt,
		arg.LastActiveAt,
		arg.ExpiresAt,
		arg.IsRevoked,
	)
	return err
}

const getActiveUserSessions = `-- name: GetActiveUserSessions :many
SELECT
  id,
  user_id,
  application_id,
  ip_address,
  user_agent,
  location,
  created_at,
  last_active_at,
  expires_at,
  is_revoked
FROM
  user_session
WHERE
  user_id = $1
  AND is_revoked = FALSE
  AND expires_at > NOW()
ORDER BY
  last_active_at DESC
`

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetActiveUserSessions(ctx context.Context, userID uuid.UUID) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, getActiveUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApplicationID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Location,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.ExpiresAt,
			&i.IsRevoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessionByID = `-- name: GetUserSessionByID :one
SELECT
  id,
  user_id,
  application_id,
  ip_address,
  user_agent,
  location,
  created_at,
  last_active_at,
  expires_at,
  is_revoked
FROM
  user_session
WHERE
  id = $1
  AND user_id = $2
`

type GetUserSessionByIDParams struct {
	ID     uuid.UUID `db:"id"`
	UserID uuid.UUID `db:"user_id"`
}

func (q *Queries) GetUserSessionByID(ctx context.Context, arg GetUserSessionByIDParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByID, arg.ID, arg.UserID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Location,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.IsRevoked,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE
  user_session
SET
  is_revoked = TRUE
WHERE
  user_id = $1
  AND is_revoked = FALSE
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeUserSessionByID = `-- name: RevokeUserSessionByID :exec
UPDATE
  user_session
SET
  is_revoked = TRUE
WHERE
  id = $1
  AND user_id = $2
`

type RevokeUserSessionByIDParams struct {
	ID     uuid.UUID `db:"id"`
	UserID uuid.UUID `db:"user_id"`
}

func (q *Queries) RevokeUserSessionByID(ctx context.Context, arg RevokeUserSessionByIDParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessionByID, arg.ID, arg.UserID)
	return err
}

const updateUserSessionLastActive = `-- name: UpdateUserSessionLastActive :exec
UPDATE
  user_session
SET
  last_active_at = NOW()
WHERE
  id = $1
`

func (q *Queries) UpdateUserSessionLastActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserSessionLastActive, id)
	return err
}
