// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profile.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const addUserProfile = `-- name: AddUserProfile :exec
INSERT INTO
    user_profile (
        user_id,
        display_name,
        first_name,
        last_name,
        phone_number,
        "address",
        photo_url
    )
VALUES
    (
        $1,
        -- user_id
        $2,
        -- display_name
        $3,
        -- first_name
        $4,
        -- last_name
        $5,
        -- phone_number
        $6,
        -- address
        $7 -- photo_url
    )
`

type AddUserProfileParams struct {
	UserID      uuid.UUID `db:"user_id"`
	DisplayName string    `db:"display_name"`
	FirstName   string    `db:"first_name"`
	LastName    string    `db:"last_name"`
	PhoneNumber *string   `db:"phone_number"`
	Address     *string   `db:"address"`
	PhotoUrl    *string   `db:"photo_url"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddUserProfile(ctx context.Context, arg AddUserProfileParams) error {
	_, err := q.db.Exec(ctx, addUserProfile,
		arg.UserID,
		arg.DisplayName,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Address,
		arg.PhotoUrl,
	)
	return err
}

const getUserProfileByUserId = `-- name: GetUserProfileByUserId :one
SELECT
    user_id,
    display_name,
    first_name,
    last_name,
    phone_number,
    "address",
    photo_url
FROM
    user_profile
WHERE
    user_id = $1
`

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetUserProfileByUserId(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserId, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Address,
		&i.PhotoUrl,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE
    user_profile
SET
    display_name = $1,
    first_name = $2,
    last_name = $3,
    phone_number = $4,
    "address" = $5,
    photo_url = $6
WHERE
    user_id = $7
`

type UpdateUserProfileParams struct {
	DisplayName string    `db:"display_name"`
	FirstName   string    `db:"first_name"`
	LastName    string    `db:"last_name"`
	PhoneNumber *string   `db:"phone_number"`
	Address     *string   `db:"address"`
	PhotoUrl    *string   `db:"photo_url"`
	UserID      uuid.UUID `db:"user_id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.DisplayName,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Address,
		arg.PhotoUrl,
		arg.UserID,
	)
	return err
}
