// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_credentials.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserCredentials = `-- name: AddUserCredentials :exec
INSERT INTO
    user_credentials (
        id,
        user_id,
        password_hash,
        password_algorithm,
        should_change_pass,
        created_at,
        updated_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
`

type AddUserCredentialsParams struct {
	ID                uuid.UUID        `db:"id"`
	UserID            uuid.UUID        `db:"user_id"`
	PasswordHash      string           `db:"password_hash"`
	PasswordAlgorithm string           `db:"password_algorithm"`
	ShouldChangePass  bool             `db:"should_change_pass"`
	CreatedAt         pgtype.Timestamp `db:"created_at"`
	UpdatedAt         *time.Time       `db:"updated_at"`
}

// ----------------------------------COMMANDS--------------------------------------
func (q *Queries) AddUserCredentials(ctx context.Context, arg AddUserCredentialsParams) error {
	_, err := q.db.Exec(ctx, addUserCredentials,
		arg.ID,
		arg.UserID,
		arg.PasswordHash,
		arg.PasswordAlgorithm,
		arg.ShouldChangePass,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserCredentialsByUserID = `-- name: GetUserCredentialsByUserID :one
SELECT
    id,
    user_id,
    password_hash,
    password_algorithm,
    should_change_pass,
    created_at,
    updated_at
FROM
    user_credentials
WHERE
    user_id = $1
`

type GetUserCredentialsByUserIDRow struct {
	ID                uuid.UUID        `db:"id"`
	UserID            uuid.UUID        `db:"user_id"`
	PasswordHash      string           `db:"password_hash"`
	PasswordAlgorithm string           `db:"password_algorithm"`
	ShouldChangePass  bool             `db:"should_change_pass"`
	CreatedAt         pgtype.Timestamp `db:"created_at"`
	UpdatedAt         *time.Time       `db:"updated_at"`
}

// ----------------------------------QUERIES--------------------------------------
func (q *Queries) GetUserCredentialsByUserID(ctx context.Context, userID uuid.UUID) (GetUserCredentialsByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByUserID, userID)
	var i GetUserCredentialsByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordAlgorithm,
		&i.ShouldChangePass,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeUserCredentials = `-- name: RemoveUserCredentials :exec
DELETE FROM
    user_credentials
WHERE
    user_id = $1
`

func (q *Queries) RemoveUserCredentials(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeUserCredentials, userID)
	return err
}

const updateUserCredentials = `-- name: UpdateUserCredentials :exec
UPDATE
    user_credentials
SET
    password_hash = $1,
    password_algorithm = $2,
    should_change_pass = $3,
    updated_at = $4
WHERE
    user_id = $5
`

type UpdateUserCredentialsParams struct {
	PasswordHash      string     `db:"password_hash"`
	PasswordAlgorithm string     `db:"password_algorithm"`
	ShouldChangePass  bool       `db:"should_change_pass"`
	UpdatedAt         *time.Time `db:"updated_at"`
	UserID            uuid.UUID  `db:"user_id"`
}

func (q *Queries) UpdateUserCredentials(ctx context.Context, arg UpdateUserCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateUserCredentials,
		arg.PasswordHash,
		arg.PasswordAlgorithm,
		arg.ShouldChangePass,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}
